tableau {
    project {
        group = "com.ldtteam"
        publisher = "LDTTeam"
        modId = "domum_ornamentum"
        versioning {
            version = environmentVariable("VERSION")
                    .orElse(property("local.version"))
            suffix = ""
        }
    }

    sourceSets {
        api {
            isPartOfPrimaryJar = true
            neogradle {
                isModSource = true
            }
        }
        main {
            dependencies {
                implementation sourceSets.named('api')
            }
        }
    }
}