org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

local.version=1.0.0-local

### Toolchain setup
javaVersion=25

### Minecraft
minecraft.version=26.2
minecraft.additionalVersions=

### Neoforge
neoforge.version=26.2.0.66
neoforge.data.runs=clientData

### Publishing
curse.id=527361