org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

modGroup=com.ldtteam
modVersion=1.0.0
modId=domum_ornamentum

forgeVersion=21.1.4
minecraftVersion=1.21.1

exactMinecraftVersion=1.21.1
additionalMinecraftVersions=1.21

jei_mcversion=1.21
jei_version=19.8.2.99

librarySourceSets=api;main;datagen;

dataGeneratorsVersion=1.20.4-0.1.57-ALPHA
usesDatagen=true

githubUrl=https://github.com/ldtteam/Domum-Ornamentum
gitUrl=https://github.com/ldtteam/Domum-Ornamentum.git
gitConnectUrl=https://github.com/ldtteam/Domum-Ornamentum.git
projectUrl=https://github.com/ldtteam/Domum-Ornamentum

curseId=527361
usesCurse=true

javaVersion=21
useJavaToolChains=true

usesParchment=true
parchmentMinecraftVersion=1.21
parchmentMappingsVersion=2024.07.28

usesResourceDataExpansionFromProjectKeys=false
