org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

local.version=1.0.0-local

### Toolchain setup
javaVersion=21

### Project
type=MOD
license=MIT
author=chisels-and-bits
modId=chiselsandbits
description=A Minecraft mod about creating endless custom decorations using in game materials.\n\nWell that's pretty broad, but its accurate, C&B takes existing blocks in your game world and lets you manipulate them together to create new custom creations, sculpting, copying, sawing, rotating, measuring and building is all possible at a micro-scale.\n\nThe possibilities are virtually endless.

### Minecraft
minecraft.version=1.21.1
minecraft.version.minimal=1.21

### Parchment
parchment.version=2024.11.17
parchment.minecraftVersion=1.21.1

### Neoforge
neoforge.version=21.1.217
neoforge.data.runs=data

### Publishing
curse.id=527361

### Dependencies:
jei_mcversion=1.21
jei_version=19.8.2.99
dataGeneratorsVersion=1.20.4-0.1.57-ALPHA