pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven {
            url = uri('https://ldtteam.jfrog.io/artifactory/tableau/')
            name = 'Tableau'
        }
    }
}

plugins {
    //TODO: Remove the .all
    id 'com.ldtteam.tableau' version '0.0.70'
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'domum-ornamentum'

