package com.ldtteam.domumornamentum.datagen.extra;

import com.ldtteam.domumornamentum.block.ModBlocks;
import com.ldtteam.domumornamentum.block.decorative.ExtraBlock;
import com.ldtteam.domumornamentum.util.Constants;
import net.minecraft.data.DataGenerator;
import com.ldtteam.domumornamentum.datagen.model.BlockStateProvider;
import com.ldtteam.domumornamentum.datagen.model.ModelFile;
import com.ldtteam.domumornamentum.datagen.DatagenContext;
import org.jetbrains.annotations.NotNull;

public class ExtraBlockStateProvider extends BlockStateProvider
{

    public ExtraBlockStateProvider(DataGenerator gen, DatagenContext exFileHelper) {
        super(gen.getPackOutput(), Constants.MOD_ID, exFileHelper);
    }

    @Override
    protected void registerStatesAndModels() {
        ModBlocks.getInstance().getExtraTopBlocks().forEach(this::registerStatesAndModelsFor);

        // These legacy standalone blocks keep their hand-authored item models
        // under models/item.  Register wrapper models so the MC 26.2 item
        // definitions generated by this provider resolve those paths.
        simpleBlockItem(ModBlocks.getInstance().getArchitectsCutter(), models().getExistingFile(modLoc("item/architectscutter")));
        simpleBlockItem(ModBlocks.getInstance().getStandingBarrel(), models().getExistingFile(modLoc("item/blockbarreldeco_standing")));
        simpleBlockItem(ModBlocks.getInstance().getLayingBarrel(), models().getExistingFile(modLoc("item/blockbarreldeco_onside")));
    }

    private void registerStatesAndModelsFor(ExtraBlock extraBlock) {
        final ModelFile cubeAll = models().cubeAll("block/extra/" + extraBlock.getType().getCategory().name().toLowerCase() + "/" + extraBlock.getRegistryName().getPath(), modLoc("block/extra/" + extraBlock.getRegistryName().getPath()));
        simpleBlockWithItem(extraBlock, cubeAll);
    }

    @NotNull
    @Override
    public String getName()
    {
        return "Extra BlockStates Provider";
    }
}
